apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: rahulsawra/python-app:latest
      
